config/routes.rb
Rails.application.routes.draw do

  resources :sessions
  get '/', to: 'sessions#index', as: 'index'
  resources :comments
  resources :gossips
  resources :users
  resources :citys
  resources :sessions, only: [:new, :create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
	has_many :users
end

app/models/comment.rb
class Comment < ApplicationRecord
	validates :content, presence: true, length: { minimum: 6 }
    belongs_to :gossip
	belongs_to :user
	has_many :likes
end

app/models/first_name_table.rb
class FirstNameTable < ApplicationRecord
end

app/models/gossip.rb
class Gossip < ApplicationRecord
	validates :title, presence: true, length: { in: 3..25 }
	validates :content, presence: true
	belongs_to :user
	has_many :comments
	has_many :taggossips
	has_many :tags, through: :taggossips
	has_many :likes
end

app/models/like.rb
class Like < ApplicationRecord
	belongs_to :user
	belongs_to :comment, optional: true
	belongs_to :gossip, optional: true
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
end

app/models/privatemessage.rb
class Privatemessage < ApplicationRecord
  belongs_to :sender, class_name: "User"
  belongs_to :recipient, class_name: "User"
end

app/models/session.rb
class Session < ApplicationRecord
end

app/models/tag.rb
class Tag < ApplicationRecord
	has_many :taggossips
	has_many :gossips, through: :taggossips
end

app/models/tag_gossip.rb
class TagGossip < ApplicationRecord
    belongs_to :gossip
    belongs_to :tag

end

app/models/taggossip.rb
class Taggossip < ApplicationRecord
	belongs_to :tag, optional: true
	belongs_to :gossip, optional: true
end

app/models/user.rb
class User < ApplicationRecord
	validates :password, presence: true, length: { minimum: 6 }
	validates :first_name, presence: true , length: { maximum: 15 }
	validates :last_name, presence: true, length: { maximum: 15 }
	validates :email, presence: true, uniqueness: true, format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "email adress please" }
	validates :age, presence: true, numericality: { only_integer: true }
	belongs_to :city
	has_many :gossips
	has_many :commments
	has_many :likes
	has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
    has_many :received_messages, foreign_key: 'recipient_id', class_name: "PrivateMessage"
	has_secure_password

end

app/controllers/citys_controller.rb
class CitysController < ApplicationController


    def index

     
        # Méthode qui récupère tous les potins et les envoie à la view index (index.html.erb) pour affichage
      end
    
      def show
        @id_users = User.find(params['id'])
        @city = @id_users.city_id
        @user = User.where(city_id: @city)
        @gossip = Gossip.where(user_id: @user)
        # Méthode qui récupère le potin concerné et l'envoie à la view show (show.html.erb) pour affichage
      end
    
      def new
        # Méthode qui crée un potin vide et l'envoie une view qui affiche le formulaire pour 'le remplir' (new.html.erb)
      end
    
      def create
        # Méthode qui créé un potin à partir du contenu du formulaire de new.html.erb, soumis par l'utilisateur
        # pour info, le contenu de ce formulaire sera accessible dans le hash params (ton meilleur pote)
        # Une fois la création faite, on redirige généralement vers la méthode show (pour afficher le potin créé)
      end
    
      def edit
        # Méthode qui récupère le potin concerné et l'envoie à la view edit (edit.html.erb) pour affichage dans un formulaire d'édition
      end
    
      def update
        # Méthode qui met à jour le potin à partir du contenu du formulaire de edit.html.erb, soumis par l'utilisateur
        # pour info, le contenu de ce formulaire sera accessible dans le hash params
        # Une fois la modification faite, on redirige généralement vers la méthode show (pour afficher le potin modifié)
      end
    
      def destroy
        # Méthode qui récupère le potin concerné et le détruit en base
        # Une fois la suppression faite, on redirige généralement vers la méthode index (pour afficher la liste à jour)
      end



end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

    def welcome
        @name =  params[:name]
    end

    def home

    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def index
      
        # Méthode qui récupère tous les potins et les envoie à la view index (index.html.erb) pour affichage
      end
    
      def show
        @users = User.all
        @id_users = User.find(params['id'])
        @city = @id_users.city_id

        # Méthode qui récupère le potin concerné et l'envoie à la view show (show.html.erb) pour affichage
      end
    
      def new
        @user = User.last
      end
    
      def create

      @user = User.new
      @user.last_name = params['last_name']
      @user.first_name = params['first_name']
      @user.email = params['user_email']
      @user.age = params['user_age']
      @user.password = params['user_password']
      @user.password_confirmation = params['password_confirmation']
      @user.description = params['user_description']
      @user.city_id = City.all.sample.id
      
      
      if @user.save # essaie de sauvegarder en base @gossip
       
        redirect_to users_path
        
      else
         render :template => 'users/new'# sinon, il render la view 
        # Méthode qui créé un potin à partir du contenu du formulaire de new.html.erb, soumis par l'utilisateur
        # pour info, le contenu de ce formulaire sera accessible dans le hash params (ton meilleur pote)
        # Une fois la création faite, on redirige généralement vers la méthode show (pour afficher le potin créé)
      end
    end
    
      def edit
        # Méthode qui récupère le potin concerné et l'envoie à la view edit (edit.html.erb) pour affichage dans un formulaire d'édition
      end
    
      def update
        # Méthode qui met à jour le potin à partir du contenu du formulaire de edit.html.erb, soumis par l'utilisateur
        # pour info, le contenu de ce formulaire sera accessible dans le hash params
        # Une fois la modification faite, on redirige généralement vers la méthode show (pour afficher le potin modifié)
      end
    
      def destroy
        # Méthode qui récupère le potin concerné et le détruit en base
        # Une fois la suppression faite, on redirige généralement vers la méthode index (pour afficher la liste à jour)
      end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/citys_helper.rb
module CitysHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def current_user
     User.find_by(id: session[:user_id])
   end
 
    def log_in(user)
     session[:user_id] = user.id
   end
 
 end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/citys/show.html.erb
<% @gossip.each do |f| %>
    <%=     f.title  %> <br>

<%=     f.content  %> <br>
<%=     f.user.first_name  %> <br>

<%end%>

app/views/users/index.html.erb
<div class='login'>
  <h2>Sign in</h2>
  <input name='username' placeholder='Email' type='text'/>
  <input id='pw' name='password' placeholder='Password' type='password'/>
  <div class='remember'>
    <input checked='' id='remember' name='remember' type='checkbox'/>
  </div>
  <input type='submit' value='Sign in'/>
  <input type='submit' value='Sign up'/>
</div>

<style>body {
  background: #2f313d;
  color: #46485c;
  font-family: sans-serif;
}

h2 {
  color: #46485c;
  font-size: 15px;
  font-weight: 600;
  text-align: center;
  margin-bottom: 10px;
}

a {
  color: #46485c;
  text-decoration: none;
}

.login {
  width: 250px;
  position: absolute;
  top: 50%;
  left: 50%;
  margin: -184px 0px 0px -155px;
  background: rgba(0,0,0,0.2);
  padding: 20px 30px;
  border-radius: 5px;
  box-shadow: 0px 1px 0px rgba(0,0,0,0.3),inset 0px 1px 0px rgba(255,255,255,0.07)
}

input[type="text"], input[type="password"] {
  width: 250px;
  padding: 25px 0px;
  background: transparent;
  border: 0;
  border-bottom: 1px solid rgba(255,255,255,0.04);
  outline: none;
  color: #46485c;
}
input[type=checkbox] {
  display: none;
}

label {
  display: block;
  position: absolute;
  margin-top: 2px;
  width: 4px;
  height: 4px;
  border-radius: 50%;
  background: #46485c;
  content: "";
  transition: all 0.3s ease-in-out;
  cursor: pointer;
  border: 3px solid #252730;
  box-shadow: 0px 0px 0px 2px #46485c;
}

#remember:checked ~ label[for=remember] {
  background: #b5cd60;
  border: 3px solid #252730;
  box-shadow: 0px 0px 0px 2px #b5cd60;
}


input[type="submit"] {
  background: #b5cd60;
  border: 0;
  width: 190px;
  height: 40px;
  border-radius: 3px;
  color: white;
  cursor: pointer;
  transition: background 0.3s ease-in-out;
}
input[type="submit"]:hover {
  background: #16aa56;
}

.forgot {
  margin-top: 30px;
  display: block;
  font-size: 11px;
  text-align: center;
  font-weight: bold;
}
.forgot:hover {
  margin-top: 30px;
  display: block;
  font-size: 11px;
  text-align: center;
  font-weight: bold;
  color: #6d7781;
}

.remember {
  padding: 30px 0px;
  font-size: 12px;
  text-indent: 25px;
  line-height: 15px;
}

::-webkit-input-placeholder {
  color: #46485c;
}

[placeholder]:focus::-webkit-input-placeholder {
  transition: all 0.2s linear;
  transform: translate(10px, 0);
  opacity: 0;
}

 
</style>

<script> //show password
$(document).ready(function(){
    $("#pw").focus(function(){
        this.type = "text";
    }).blur(function(){
        this.type = "password";
    })   
});

//Placeholder fixed for Internet Explorer
$(function() {
	var input = document.createElement("input");
	if(('placeholder' in input)==false) { 
		$('[placeholder]').focus(function() {
			var i = $(this);
			if(i.val() == i.attr('placeholder')) {
				i.val('').removeClass('placeholder');
				if(i.hasClass('password')) {
					i.removeClass('password');
					this.type='password';
				}			
			}
		}).blur(function() {
			var i = $(this);	
			if(i.val() == '' || i.val() == i.attr('placeholder')) {
				if(this.type=='password') {
					i.addClass('password');
					this.type='text';
				}
				i.addClass('placeholder').val(i.attr('placeholder'));
			}
		}).blur().parents('form').submit(function() {
			$(this).find('[placeholder]').each(function() {
				var i = $(this);
				if(i.val() == i.attr('placeholder'))
					i.val('');
			})
		});
	}
	});


</script>

app/views/users/new.html.erb
CREATION D'UN NOUVEL UTILISATEUR

<div class="row m-3">
	<% if @user.errors.any? %>
	<div class="alert alert-danger" role="alert">
	  <p>Nous n'avons pas réussi à créer l'utilisateur pour la (ou les) raison(s) suivante(s) :</p>
	  <ul>
	    <% @user.errors.full_messages.each do |message| %>
	      <li><%= message %></li>
	    <% end %>
	  </ul>
	  </div>
      
	<% end %>
</div>
<% if @i == "1" %>
      <div class="alert alert-success" role="alert">
	  <p> YEAH BRAAA</p>
	  
	  </div>
      <% end %>
      </div>


<div class="row m-3">
		<div class="col-sm-12 col-md-6 offset-md-3">
		  <%= form_tag("/sessions", method: "post") do %>

		  <%= label_tag(:last_name, "Surname:") %>
		  <%= text_field_tag(:last_name, "", :class => 'form-control') %>
		  <br>
		  <%= label_tag(:first_name, "Name:") %>
		  <%= text_field_tag(:first_name, "", :class => 'form-control') %>
		  <br>
          <%= label_tag(:user_email, "Mail:") %>
		  <%= text_field_tag(:user_email, "", :class => 'form-control') %>
		  <br>
          <%= label_tag(:user_age, "Age:") %>
		  <%= text_field_tag(:user_age, "", :class => 'form-control') %>
		  <br>
          
          <%= label_tag(:user_password, "Password:") %>
		  <%= text_field_tag(:user_password, "", :class => 'form-control') %>
		  <br>
          <%= label_tag(:password_confirmation, "Confirm it:") %>
		  <%= text_field_tag(:password_confirmation, "", :class => 'form-control') %>
		  <br>
          <%= label_tag(:user_description, "Description:") %>
		  <%= text_area_tag(:user_description, "", :class => 'form-control') %>
		  <br>
		  <%= submit_tag("Créer", :class => "btn btn-success") %>
		  </div>
	<% end %>
</div>

<div class="row m-3">

app/views/users/show.html.erb
<div class="card">
  <div class="card-header">
  <%=  @id_users.first_name %>,<%=  @id_users.last_name %>
  </div>
  <div class="card-body">
    <h5 class="card-title">Nom prénom :  <%=  @id_users.email %> </h5>
    <p class="card-text">Description : <%=  @id_users.description %><br></p>
    <a href="#" class="btn btn-primary">  age : <%=  @id_users.age %></a>
        <a href="<%= city_path(@id_users.city_id)  %>" class="btn btn-primary">  City : <%=  city = @id_users.city.name %></a>
  </div>
</div>