config/routes.rb
Rails.application.routes.draw do

  resources :sessions
  get '/', to: 'sessions#index', as: 'index'
  resources :comments
  resources :gossips
  resources :users
  resources :citys
  resources :sessions, only: [:new, :create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
	has_many :users
end

app/models/comment.rb
class Comment < ApplicationRecord
	validates :content, presence: true, length: { minimum: 6 }
    belongs_to :gossip
	belongs_to :user
	has_many :likes
end

app/models/first_name_table.rb
class FirstNameTable < ApplicationRecord
end

app/models/gossip.rb
class Gossip < ApplicationRecord
	validates :title, presence: true, length: { in: 3..25 }
	validates :content, presence: true
	belongs_to :user
	has_many :comments
	has_many :taggossips
	has_many :tags, through: :taggossips
	has_many :likes
end

app/models/like.rb
class Like < ApplicationRecord
	belongs_to :user
	belongs_to :comment, optional: true
	belongs_to :gossip, optional: true
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
end

app/models/privatemessage.rb
class Privatemessage < ApplicationRecord
  belongs_to :sender, class_name: "User"
  belongs_to :recipient, class_name: "User"
end

app/models/session.rb
class Session < ApplicationRecord
end

app/models/tag.rb
class Tag < ApplicationRecord
	has_many :taggossips
	has_many :gossips, through: :taggossips
end

app/models/tag_gossip.rb
class TagGossip < ApplicationRecord
    belongs_to :gossip
    belongs_to :tag

end

app/models/taggossip.rb
class Taggossip < ApplicationRecord
	belongs_to :tag, optional: true
	belongs_to :gossip, optional: true
end

app/models/user.rb
class User < ApplicationRecord
	validates :password, presence: true, length: { minimum: 6 }
	validates :first_name, presence: true , length: { maximum: 15 }
	validates :last_name, presence: true, length: { maximum: 15 }
	validates :email, presence: true, uniqueness: true, format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "email adress please" }
	validates :age, presence: true, numericality: { only_integer: true }
	belongs_to :city
	has_many :gossips
	has_many :commments
	has_many :likes
	has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
    has_many :received_messages, foreign_key: 'recipient_id', class_name: "PrivateMessage"
	has_secure_password

end

app/controllers/citys_controller.rb
class CitysController < ApplicationController


    def index

     
        # Méthode qui récupère tous les potins et les envoie à la view index (index.html.erb) pour affichage
      end
    
      def show
        @id_users = User.find(params['id'])
        @city = @id_users.city_id
        @user = User.where(city_id: @city)
        @gossip = Gossip.where(user_id: @user)
        # Méthode qui récupère le potin concerné et l'envoie à la view show (show.html.erb) pour affichage
      end
    
      def new
        # Méthode qui crée un potin vide et l'envoie une view qui affiche le formulaire pour 'le remplir' (new.html.erb)
      end
    
      def create
        # Méthode qui créé un potin à partir du contenu du formulaire de new.html.erb, soumis par l'utilisateur
        # pour info, le contenu de ce formulaire sera accessible dans le hash params (ton meilleur pote)
        # Une fois la création faite, on redirige généralement vers la méthode show (pour afficher le potin créé)
      end
    
      def edit
        # Méthode qui récupère le potin concerné et l'envoie à la view edit (edit.html.erb) pour affichage dans un formulaire d'édition
      end
    
      def update
        # Méthode qui met à jour le potin à partir du contenu du formulaire de edit.html.erb, soumis par l'utilisateur
        # pour info, le contenu de ce formulaire sera accessible dans le hash params
        # Une fois la modification faite, on redirige généralement vers la méthode show (pour afficher le potin modifié)
      end
    
      def destroy
        # Méthode qui récupère le potin concerné et le détruit en base
        # Une fois la suppression faite, on redirige généralement vers la méthode index (pour afficher la liste à jour)
      end



end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController


    def index
         session[:user_id] = {first_name: 'Jonathon', id: 4}

        @gossips = Gossip.all
        @session = session[:user_id]
        # Méthode qui récupère tous les potins et les envoie à la view index (index.html.erb) pour affichage
      end
    
      def show
        @id_gossips = Gossip.find(params['id'])
        @comments = Comment.all
        @comment_set = Comment.where(gossip_id: @id_gossips)
        @comment_author = User.where(id: @id_gossips.user_id)

        # Méthode qui récupère le potin concerné et l'envoie à la view show (show.html.erb) pour affichage
      end
    
   
   
    
      def edit
        @id_gossips = Gossip.find(params['id'])

        # Méthode qui récupère le potin concerné et l'envoie à la view edit (edit.html.erb) pour affichage dans un formulaire d'édition
      end
    
      def update
        @id_gossips = Gossip.find(params['id'])
        gossip_params = params.require(:gossip).permit(:title, :content)
        @id_gossips.update(gossip_params)
        redirect_to gossip_path
        # Méthode qui met à jour le potin à partir du contenu du formulaire de edit.html.erb, soumis par l'utilisateur
        # pour info, le contenu de ce formulaire sera accessible dans le hash params
        # Une fois la modification faite, on redirige généralement vers la méthode show (pour afficher le potin modifié)
      end
    
      def destroy
        @gossip = Gossip.find(params['id'])
        @gossip.destroy

        redirect_to gossips_path
        # Méthode qui récupère le potin concerné et le détruit en base
        # Une fois la suppression faite, on redirige généralement vers la méthode index (pour afficher la liste à jour)
      end

      def new
        @gossip = Gossip.new
        # Méthode qui crée un potin vide et l'envoie une view qui affiche le formulaire pour 'le remplir' (new.html.erb)
      end
    
      def create
   
        @gossip = Gossip.create(gossip_params)
        redirect_to gossips_path
        # Méthode qui créé un potin à partir du contenu du formulaire de new.html.erb, soumis par l'utilisateur
        # pour info, le contenu de ce formulaire sera accessible dans le hash params (ton meilleur pote)
        # Une fois la création faite, on redirige généralement vers la méthode show (pour afficher le potin créé)
      end


      private 

      def gossip_params
          params.require(:gossip).permit(:title, :content, :user_id)

      end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

    def welcome
        @name =  params[:name]
    end

    def home

    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/citys_helper.rb
module CitysHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def current_user
     User.find_by(id: session[:user_id])
   end
 
    def log_in(user)
     session[:user_id] = user.id
   end
 
 end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/gossips/edit.html.erb
<h1>Editer votre potins </h1>


<%= form_for @id_gossips do |f| %>

<div> 

    <label> Titre </label>
    <%= f.text_field :title %>

</div>
<div> 

    <label> Content </label>
    <%= f.text_field :content %>

</div>


<button class="btn " type="submit">Edit</button>
<% end %>

app/views/gossips/index.html.erb
<center><h1>LA SOUPE DES POTINS</h1></center>

  <a class="btn" href="<%=  new_gossip_path %>">Creer un gossip</a>

  <div class="row">
  <% @gossips.each do |gossip| %>

    <div class="col s4">
      <div class="card #00796b teal darken-2 ">

        <div class="card-content white-text">
          <span class="card-title"><%= gossip.id %>, <%= gossip.title %></span>
          <p><%= gossip.content %></p>
        </div>
        <div class="card-action">
          <a href="#"><%= gossip.user.first_name %>, <%= gossip.user.last_name %></a>
 
 <div>  <a href="<%= gossip_path(gossip.id) %>" class="btn btn-primary waves-teal">Afficher</a>
 <a class="btn" href="<%= edit_gossip_path(gossip.id) %>">Editer</a>

  <a class="btn red" href="<%= gossip_path(gossip.id) %>" data-method="DELETE" data-confirm="Vous êtes sur ????">Supprimer</a></div>

        </div>
      </div>
    </div>
    <% end %>
  </div>
            




<style> 

body {
    background-image : linear-gradient(#f7f6f6,#f7f6f6);
    background-size : cover;
    background-repeat : no-repeat;
    background-attachment : fixed;
}

  h1 {
    color : #fb75bf;

  }

</style>

app/views/gossips/new.html.erb
  
   <h1>Creer des potins </h1>


<%= form_for @gossip do |f| %>

<div> 

    <label> Titre </label>
    <%= f.text_field :title %>

</div>
<div> 

    <label> Content </label>
    <%= f.text_field :content %>

</div>
<div > 

    <label> user </label>
    <%= f.text_field :user_id  %>

</div>


<button class="btn " type="submit">Creer</button>
<% end %>

app/views/gossips/show.html.erb
  <div class="row">

    <div class="col s4">
      <div class="card #00796b teal darken-2 ">

        <div class="card-content white-text">
          <span class="card-title">Title : <%= @id_gossips.title %>, <br> Author : <%= @id_gossips.user.first_name %></span>
          <p>Content : <%= @id_gossips.content %></p>
                  <p>City :  <%= @id_gossips.user.city.name %></p>

        </div>
        <div class="card-action">
    <a  href="<%= user_path(@id_gossips.user_id)%>" class="btn btn-primary"  ><%= @id_gossips.user.first_name %> </a> <button class="btn"><a href="/gossips">Revenir en arriere</a></button>
<a class="btn" href="<%= edit_gossip_path(@id_gossips.id) %>">Editer</a>
    <div> <%= @id_gossips.created_at%>
    </div>
      </div>
    </div>
  </div>

    
   <h1>un petit commentaire ? </h1>


<%  @comment_set.each do |f| %>
<div>

    <label> Content </label>
    <%= f.content %>
    <%= f.id %>

</div>

<% end %>
<%  @comment_author.each do |a| %>
    <label> Author </label>

  <%= a.first_name %><br>
  <a class="btn " href="<%= edit_comment_path %>">Par la pour modifier </a>

  <% end %>
   <a class="btn " href="<%= new_comment_path %>">Commenter </a>